export const METADATA_PROJECTION = 'METADATA_PROJECTION';
export const METADATA_CATCH_UP_SUBSCRIPTION = 'METADATA_CATCH_UP_SUBSCRIPTION';
export const METADATA_PERSISTENT_SUBSCRIPTION = 'METADATA_PERSISTENT_SUBSCRIPTION';
