name: "GitHub Registry | @purrfect-tools/common"

on:
  push:
    tags:
      - 'common-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn workspace @purrfect-tools/common test
      - run: |
          echo @Rzial:https://npm.pkg.github.com/ > ./.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> ./.npmrc
      - run: yarn workspace @purrfect-tools/common npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
