name: "GitHub Registry | @purrfect-tools/event-store-client"

on:
  push:
    tags:
      - 'event-store-client-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn workspace @purrfect-tools/event-store-client test
      - run: |
          echo @lexacode:https://npm.pkg.github.com/ > build/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
      - run: yarn workspace @purrfect-tools/event-store-client npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
